// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qajqldhqyeereflnxduj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhanFsZGhxeWVlcmVmbG54ZHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDU1MzUsImV4cCI6MjA2OTkyMTUzNX0.RgIqpF08tlabSVX4PxvT-7sqbyksmjhkfZKI4o6Czpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});